site_name: My Notes
site_author: Shoaib Shaikh
site_url: https://shoaibashk.github.io/notes
site_description: My NOtes for Exams

copyright: |
  Copyright &copy; 2017 - 2020 <b>Shoaib Shaikh 😎</b>

plugins:
  - search
  - mkdocs-jupyter:
      include_source: True
      execute: True

  - minify:
      minify_html: true

theme: 
  name: null
  custom_dir: docs/material
  language: en
  icon:
    logo: material/book-open-page-variant
  palette:
    # scheme: slate
    primary: deep orange
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs
    - instant




markdown_extensions:
  - mdx_math
  - codehilite
  # - toc:
  #     permalink: True
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg






# extra_javascript:
#   - javascripts/config.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_javascript:
#     - javascripts/config.js
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML



extra:
#   disqus: "https-shoaibashk-github-io"
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shoaibashk/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/shoaibashk/
    - icon: fontawesome/brands/github
      link: https://github.com/Shoaibashk



nav:
  - Home: index.md
  - MCN: MCN/index.md
   
 